const hihopMaskwipetransitionEffects = [
  {
    prompt:
      'Create a dynamic wipe transition effect that emulates classic hip-hop video scratch/turntable motions. Think of this as a vinyl record scratching back and forth - the transition should use SVG paths that create jagged, angular wipes moving horizontally with a stutter-step rhythm. The wipe should reveal content underneath with a sharp, geometric edge that occasionally reverses direction (like a DJ scratching). Use multiple overlapping SVG masks with different timing offsets to create a layered, glitchy feel. The animation should feel aggressive and rhythmic, matching the percussive nature of hip-hop beats. Include subtle rotation on the wipe edge to simulate the circular motion of a turntable. Add a slight bounce-back effect at the end of each wipe segment, as if the DJ is pulling the record back. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts',
    technicalSpecs:
      "Structure: BaseLayout container with 'relative w-full h-full overflow-hidden' containing multiple SVG elements with clipPath definitions. Use absolute positioned layers with 'absolute inset-0' for each mask layer. Animation: CSS keyframes with cubic-bezier(0.77, 0, 0.175, 1) for sharp, snappy movements. Duration: 800-1200ms total with staggered 50ms delays between layers. Use transform: translateX() and rotate() for GPU acceleration. Add will-change: transform to mask elements. Create 3-4 different clipPath shapes using SVG path elements with jagged, angular designs. Apply 'pointer-events-none' to prevent interaction issues.",
  },
  {
    prompt:
      'Design a graffiti spray-paint reveal transition that builds up the next scene as if being spray-painted onto a wall. The effect should use SVG filters to create a realistic spray texture with particles that scatter and accumulate. Start with small, concentrated spray bursts that gradually expand into larger coverage areas. Include drip effects using SVG paths that animate downward with gravity-based easing. The spray pattern should be randomized but controlled, creating an organic street-art feel. Add subtle color bleeding at the edges using SVG blur filters. Incorporate a slight shake/vibration to the spray areas to simulate the hand movement of a graffiti artist. The reveal should happen in multiple passes, like an artist layering colors. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts',
    technicalSpecs:
      "Use BaseLayout with 'relative w-full h-full bg-black' as base. Create SVG defs with multiple feTurbulence and feDisplacementMap filters for spray texture. Structure: 5-7 absolute positioned SVG layers with 'absolute inset-0 w-full h-full'. Use clipPath with circle elements of varying sizes animated via SMIL or CSS. Animation timing: 1500-2000ms with ease-out for natural spray accumulation. Add transform: scale() from 0 to 1 for each spray burst with staggered delays (100-200ms). Use opacity transitions from 0.7 to 1 for paint buildup effect. Apply 'mix-blend-mode-multiply' for color layering. Performance: limit to 3 simultaneous animating layers using animation-delay.",
  },
  {
    prompt:
      "Build a shattered glass transition where the current scene breaks into triangular shards that rotate and fall away to reveal the next scene. Each shard should have slightly different physics - some spinning faster, others falling with more weight. Use SVG polygons to create 20-30 irregular triangle shapes that tessellate to form the complete frame. Add a subtle prismatic effect using SVG filters that creates rainbow light refractions on the shard edges. The shatter should originate from a impact point (customizable) with shards closer to the impact moving first. Include a slight camera shake effect at the moment of impact using the entire container's transform. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts",
    technicalSpecs:
      "Container: BaseLayout with 'relative w-full h-full overflow-hidden' and a transform-based shake animation (2-3 quick translateX/Y movements). Create SVG with 20-30 polygon elements, each with unique clipPath IDs. Use 'absolute inset-0' for SVG container. Each polygon gets custom CSS with transform: rotateX() rotateY() rotateZ() translateZ() for 3D effect. Add 'transform-style-preserve-3d' to container. Timing: stagger animations based on distance from impact point (calculated via data attributes). Use cubic-bezier(0.55, 0.055, 0.675, 0.19) for glass-like sharp initial movement. Duration: 1200-1600ms total. Add backdrop-filter: blur(2px) to shards for depth. Use will-change: transform and transform: translateZ(0) for GPU optimization.",
  },
  {
    prompt:
      "Create a liquid morph transition that simulates thick paint or honey flowing across the screen. The effect should use SVG paths with smooth, organic curves that undulate and flow naturally. The leading edge of the transition should bulge and contract like a viscous liquid being poured. Use multiple layers of flowing shapes with different speeds to create depth - faster thin streams on top, slower thick base layer underneath. Add surface tension effects where the liquid pulls together and creates temporary holes that close up. Include subtle color gradients that shift as the liquid moves, suggesting depth and volume. The flow should respond to 'gravity' by moving faster at the bottom of the screen. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts",
    technicalSpecs:
      "Base structure: BaseLayout with 'relative w-full h-full overflow-hidden bg-gray-900'. Create 3 SVG layers with 'absolute inset-0 w-full h-full'. Use SVG path with animated d attribute for morphing shapes (via CSS or SMIL). Bottom layer: 'z-10', middle: 'z-20', top: 'z-30'. Apply different timing functions - bottom: cubic-bezier(0.45, 0.05, 0.55, 0.95), top: cubic-bezier(0.25, 0.46, 0.45, 0.94). Duration: 1800-2400ms with 200ms stagger between layers. Use SVG linearGradient with animated stop-color for color shifts. Add filter: blur(1px) to middle layer for depth. Implement clipPath animation for reveal effect. Performance: use transform: translateX() for main movement, animate path d attribute sparingly.",
  },
  {
    prompt:
      'Develop a glitch-hop inspired data corruption transition that breaks the screen into horizontal scan lines that shift, distort, and reassemble. Each scan line should have random horizontal displacement, creating a VHS tracking error aesthetic. Add RGB color channel separation where lines briefly split into red, green, and blue components before snapping back together. Include digital noise bursts using SVG filters that appear as pixelated static. The glitch should intensify in the middle of the transition with more aggressive distortions, then stabilize as the new scene locks in. Add occasional full-frame flashes and inversions for dramatic effect. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts',
    technicalSpecs:
      "Container: BaseLayout with 'relative w-full h-full overflow-hidden bg-black'. Create 20-30 horizontal div strips with 'absolute w-full left-0' and calculated top positions. Each strip: 'h-[5%]' or calculated height. Apply random translateX animations: transform: translateX(random -20% to 20%). Use CSS custom properties for randomization. Add ::before and ::after pseudo-elements for RGB splits with 'absolute inset-0' and mix-blend-mode. Timing: 600-1000ms with steps(4) for digital feel. Create SVG filter with feTurbulence and feColorMatrix for noise. Flash effect: full-screen div with 'absolute inset-0 bg-white pointer-events-none' animated opacity. Use animation-iteration-count for glitch loops. GPU optimization: transform: translateZ(0) on strips.",
  },
  {
    prompt:
      "Design a kinetic typography transition where bold, 3D extruded letters spell out transition words (like 'BREAK', 'CUT', 'SWITCH') while rotating through 3D space. The letters should have a metallic, chrome finish using SVG gradients and should cast dynamic shadows. As the letters rotate, they should reveal the next scene through their negative space. The typography should have a strong perspective distortion as if viewed through a wide-angle lens. Add motion blur to the fastest-moving parts using SVG filters. The letters should slam into place with a slight elastic overshoot, creating impact. Include particle effects that burst from impact points. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts",
    technicalSpecs:
      "Structure: BaseLayout with 'relative w-full h-full overflow-hidden perspective-[1000px]'. Create individual letter containers with 'absolute transform-style-preserve-3d'. Each letter: multiple divs for 3D extrusion with 'absolute' positioning and calculated translateZ values. Front face: 'bg-gradient-to-br from-gray-300 to-gray-600'. Sides: 'bg-gray-800'. Use transform: rotateY() rotateX() translateZ() for 3D rotation. Animation: 1000-1400ms with cubic-bezier(0.68, -0.55, 0.265, 1.55) for elastic overshoot. Add text-shadow for depth. Create SVG filter for motion blur using feGaussianBlur with animated stdDeviation. Particles: absolutely positioned divs with 'w-2 h-2 bg-white rounded-full' animated with transform: translate() scale(). Performance: use will-change: transform on animated elements.",
  },
  {
    prompt:
      'Build a vinyl record spin transition that simulates a record being placed on a turntable and starting to spin. The scene should morph into circular grooves that spiral inward while rotating. Use concentric SVG circles with varying stroke-widths to create the groove effect. The rotation should start slow and accelerate to normal playing speed (33⅓ RPM). Add a subtle needle drop effect with a thin line that traces along the grooves. Include realistic vinyl texture using SVG patterns with slight imperfections and dust particles. The center label should remain visible and rotate independently, potentially displaying transition metadata. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts',
    technicalSpecs:
      "Container: BaseLayout with 'relative w-full h-full flex items-center justify-center bg-gray-950'. Main record: div with 'relative w-[80%] aspect-square max-w-[600px]'. Create SVG with viewBox='0 0 100 100' and 'absolute inset-0 w-full h-full'. Generate 30-40 concentric circle elements with incrementing r attributes. Apply rotation: transform: rotate() with animation-duration: 1800ms (33 RPM equivalent). Use animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1) for acceleration. Needle: absolute positioned div with 'w-[2px] h-1/3 bg-gray-400' and transform-origin: top. Add SVG pattern for vinyl texture with feNoise filter. Center label: div with 'absolute inset-[35%] rounded-full bg-red-600' and counter-rotation. Clip-path the rotating content for scene reveal.",
  },
  {
    prompt:
      'Create a street-style stencil transition where the next scene is revealed through spray-painted stencil cutouts that appear sequentially. Each stencil should slam down with a slight bounce animation, then spray paint fills the cutout area with a mist effect. Use hip-hop iconography for stencil shapes - microphones, turntables, boomboxes, crowns, etc. The spray effect should include overspray that goes slightly outside the stencil boundaries for realism. Add paint drips that run down from heavily sprayed areas. The stencils should layer and overlap, creating a complex collage effect. Include subtle paper texture on the stencil edges. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts',
    technicalSpecs:
      "Base: BaseLayout with 'relative w-full h-full overflow-hidden bg-gray-800'. Create 5-7 stencil layers with 'absolute inset-0 pointer-events-none'. Each stencil: SVG with custom path shapes defining cutouts. Use clipPath and mask combinations for reveal effect. Stencil drop animation: transform: translateY(-120%) to translateY(0) with bounce timing function: cubic-bezier(0.34, 1.56, 0.64, 1). Duration: 400ms per stencil with 200ms stagger. Spray effect: animated radial-gradient in mask, transitioning from transparent to opaque. Add ::after pseudo-element for overspray with filter: blur(4px). Drips: separate SVG paths with animated strokeDashoffset. Use mix-blend-mode: multiply for layering. Performance: stagger animations to limit simultaneous transitions.",
  },
  {
    prompt:
      "Develop a boom-bap beat visualizer transition where geometric shapes pulse and transform in sync with an implied rhythm. Create a grid of squares that morph into circles, then triangles, following a 4/4 beat pattern. Each shape should have individual scaling and rotation animations that create a wave effect across the grid. Use SVG filters to add a subtle glow that intensifies on the 'kick' beats. The shapes should occasionally break formation and scatter before snapping back into grid alignment. Add RGB color shifts that cycle through hip-hop associated colors (gold, purple, green). The transition should feel like it's responding to bass frequencies. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts",
    technicalSpecs:
      "Container: BaseLayout with 'relative w-full h-full overflow-hidden bg-black grid grid-cols-8 grid-rows-6 gap-2 p-4'. Each cell: div with 'relative w-full h-full flex items-center justify-center'. Shapes: SVG elements with 'w-full h-full' containing path that morphs between shapes. Use CSS custom properties for staggered animations based on grid position. Base animation: transform: scale() rotate() with duration: 400ms (150 BPM). Apply different animation-delay calculated from data-row and data-col attributes. Glow effect: SVG filter with feGaussianBlur and feColorMatrix. Color animation: animate fill with steps(3) for sharp color changes. Scatter effect: occasional transform: translate(random) with elastic return. Use will-change: transform for all animated shapes. Limit concurrent animations with animation-play-state toggling.",
  },
  {
    prompt:
      'Design a wall-tag transition inspired by wildstyle graffiti where abstract, interlocking letters and shapes slide across the screen in layers. Each layer should move at different speeds creating a parallax effect. The shapes should be bold with thick black outlines and vibrant fill colors. Use SVG paths to create complex, angular letterforms that are barely legible but visually striking. Add 3D effects using drop shadows and beveled edges. The transition should include spray can sound effect visualizations - small particle bursts at random positions. Include dripping paint effects from certain letters. The overall motion should be smooth but with sudden direction changes, mimicking the flow of creating graffiti. Make sure to generate them in components/editor/presets/registry/private2 folder and import and attach it in components/editor/presets/registry/registry/presets-registry.ts',
    technicalSpecs:
      "Base: BaseLayout with 'relative w-full h-full overflow-hidden bg-gray-100'. Create 4-5 parallax layers with 'absolute w-[150%] h-full' and different z-index values. Each layer: SVG with complex path elements defining abstract letterforms. Apply different transform: translateX() speeds - back layer: 2000ms, front: 800ms. Use linear timing for smooth continuous motion. Outlines: stroke-width='3' stroke='black' stroke-linejoin='round'. Fills: use linearGradient with bright colors. 3D effect: multiple offset paths with decreasing opacity for depth. Drop shadow: filter: drop-shadow(4px 4px 8px rgba(0,0,0,0.3)). Particles: absolute divs with 'w-1 h-1 rounded-full' animated with scale and opacity. Drips: SVG paths with animated stroke-dasharray. Performance: use transform: translateZ(0) for layer compositing.",
  },
];
